### ISSUE TITLE
Issue with Literal data type

### ISSUE THREAD

**Issue by aguinane** [EricWebsmith/pydantic-2-mermaid#3]
Making use of a `Literal` for a variable breaks the pydantic parser.
https://docs.pydantic.dev/latest/api/standard_library_types/#typingliteral

Adding a try except when getting `v.__name__` fixed it, although the types aren't coming across. 

```python
def _get_name(v: Type[Any]) -> str:
    """get name from type"""
    if v in base_types:
        return v.__name__

    origin = get_origin(v)
    if origin is None:
        try:
            return v.__name__
        except AttributeError:
            return ''
```

**Comment by EricWebsmith** [comment]
Literal is now supported in v0.6.0
