### ISSUE TITLE
Add option to normalize chart in command line utility

### ISSUE THREAD

**Issue by bill-smith-vertiv** [EricWebsmith/pydantic-2-mermaid#8]
Move the normalize_chart() functionality from there: 
https://github.com/EricWebsmith/pydantic-2-mermaid/blob/9348a6f1f01877f66cb33f173017ba1cc12f601a/tests/utils.py into the base generator add a command line option to normalize the output chart when using the CLI

**Comment by EricWebsmith** [comment]
Hi Bill, 
`normalize_chart` will only sort the lines alphabetically. it is only useful in tests to compare the actual chart and the expected chart. I will rename this function later so people will not be confused. 

What do you think `normalize_chart` do? I am closing this one. you can open another issue and let me know what you want.
